# compareFiles.R
# Analyzes the rgroup.in, species.in, sxwprod_v2.in, and sxwphen.in files
# generated by rSFSTEP2.

# Security measure:
# Prevent this program from running outside of the DIST directory ##
stopifnot(endsWith(getwd(), "STEPWAT_DIST"))

# A useful function when adding lines to the mean monthly temperature graph.
addTemperatureLine <- function(temperature_values, color){
  lines(x = c(1:12), 
        y = temperature_values, 
        col = color, 
        lwd = 2)
}

addTemperaturePoint <- function(temperature_values, color, symbol){
  points(x = c(1:12), 
         y = temperature_values, 
         col = color, 
         pch = symbol, 
         cex = 3, lwd = 4)
}

# Convert a file name to an index in an array in which the row names are climate conditions
fileName2climateIndex <- function(fileName, climateArray){
  return <- 0
  for(i in 1:nrow(climateArray)){
    if(grepl(fileName, rownames(climateArray)[i])){
      return <- i
    }
  }
  return
}

# number of files written to each PNG image. If "Current" 
# exists it will be written to every file as well (regardless of this 
# value), making the total (files.per.graphic + 1) files.
files.per.graphic <- 9

################### Make an output directory #######################
if(!file.exists("output")){
  system("mkdir output")
}

# Colors for each file. The number of colors required is (files.per.graphic + 2)
# to account for "original" and "Current".
colors <- c("blue", "black", "red", "green", "orange", "green4", 
            "brown", "purple", "aquamarine", "pink", "grey")
 
#####################################################################################
############################# Analyze RGroup files ##################################
#####################################################################################
if(!file.exists("output/rgroup_comparisons")){
  system("mkdir output/rgroup_comparisons")
}
 
################## Locate all rgroup.in files ######################
rgroup.files <- list.files(".", pattern = "rgroup")

################### Remove the template file #######################
rgroup.files <- rgroup.files[!grepl(rgroup.files, pattern = "rgroup_template.in")]

all.group.parameters <- list()
rgroup.names <- c()

################ Loop through all rgroup.in files ##################
for(index in 1:length(rgroup.files)){
  ####################### Read an RGroup file ######################
  rgroup_data <- read.table(rgroup.files[index], fill = TRUE)
  
  # Line will keep track of our location in the file. This is necessary because R
  # cannot handle the "[end]" delimiter we use in STEPWAT2 files.
  line <- 1
  
  ##### Read the first table (all group parameters like space) #####
  all.group.parameters[[index]] <- list()
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], 
                                   as.character))
    rgroup.names[line] <- as.character(rgroup_data[line, 1])
    all.group.parameters[[index]][[line]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
}

####### Compress lists of lists of vectors into 3d arrays ##########
for(i in 1:length(all.group.parameters)){
  all.group.parameters[[i]] <- matrix(unlist(all.group.parameters[[i]]), 
                                      nrow = length(all.group.parameters[[i]]), 
                                      byrow = TRUE)
}
all.group.parameters <- simplify2array(all.group.parameters)

space.values <- data.frame(nrow = (length(all.group.parameters[1,1,]) * length(all.group.parameters[,1,1])),
                           ncol = 3);

number.rgroups <- length(all.group.parameters[,1,1])

for(i in 1:length(all.group.parameters[1,1,])){
  space.values[(i*number.rgroups-number.rgroups+1):(i*number.rgroups), 3] <- all.group.parameters[,1,i]
}

space.values[ ,1] <- rep(rgroup.files, each = number.rgroups)
space.values[ ,2] <- rep(rgroup.names, times = nrow(space.values) / length(rgroup.names))
colnames(space.values) <- c("File", "RGroup", "Delta Space")

################# Read original space values #######################
space.original <- read.csv("space_original_values.csv")

########## Create graphics and calculate differences ###############
if(!file.exists("output/rgroup_comparisons/graphics")){
  system("mkdir output/rgroup_comparisons/graphics")
}
for(column in 1:ncol(space.original)){
  original.filename <- colnames(space.original)[column]
     
  # Create a folder specific to this original input
  if(!file.exists(paste0("output/rgroup_comparisons/graphics/", original.filename))){
    system(paste0("mkdir output/rgroup_comparisons/graphics/", original.filename))
  }
  
  all.space.values <- space.values[grep(original.filename, space.values[,1]), ]
  number.files <- length(unique(all.space.values[,1]))
  
  for(startFile in seq(from = 1, to = number.files,
                       by = files.per.graphic)){
    space.temp <- all.space.values[(number.rgroups * (startFile-1) + 1):
                                     min((number.rgroups 
                                          * (startFile 
                                             + files.per.graphic - 1)), number.files * number.rgroups), ]
    for(rgroup in 1:nrow(space.original)){
      rgroup.space.values <- space.temp[grep(space.temp[rgroup,2], space.temp[,2]), ]
      rgroup.space.files <- c()
      for(filename in rgroup.space.values[,1]){
        tmp <- strsplit(filename, "\\.")
        tmp <- tmp[[1]][8:(length(tmp[[1]])-1)]
        rgroup.space.files <- c(rgroup.space.files,paste(tmp, collapse = "."))
      }
      
      png(paste0("output/rgroup_comparisons/graphics/", 
                  original.filename, "/", 
                  rgroup.space.values[1,2],
                  ".", startFile, "-",
                  startFile + files.per.graphic - 1,
                  ".space.graph.png"), 
          width = 1080, height = 800)
      
      barplot(rgroup.space.values[,3],
              width = rep(1, nrow(rgroup.space.values)),
              xlab = "Files", ylab = "Space Value",
              main = paste0(rgroup.space.values[1,2],
                            " Space values.\n Original value was ",
                            space.original[rgroup, column]),
              col = colors[1:length(rgroup.space.files)],
              ylim = c(0, (max(rgroup.space.values[,3])*1.4)), lwd = 3)
              
      legend("topright",
             rgroup.space.files,
             col = colors[1:length(rgroup.space.files)],
             pch = 15)
      
      dev.off()
    }
  }
      
  all.space.values <- space.values[grep(original.filename, space.values[,1]),3]
  all.space.values <- all.space.values - rep(space.original[ ,column])
  space.values[grep(original.filename, space.values[,1]),3] <- all.space.values
}
            
###################### Write output files ##########################
write.csv(space.values, 
          "output/rgroup_comparisons/space.csv",
          row.names = FALSE)

####################################################################################
########################### Compare swxphen.in files ###############################
####################################################################################
if(!file.exists("output/sxwphen_comparisons")){
  system("mkdir output/sxwphen_comparisons")
}

####################### Locate the files ###########################
phen.files <- list.files(".", pattern = "sxwphen")

##################### Store the original CSV #######################
phen.original <- read.csv("../../inputs/InputData_Phenology.csv", row.names = 1)
temperature.original <- read.csv("../../inputs/InputData_MonthlyTemp.csv", row.names = 1)
temperature.derived <- read.csv("temperature.csv", row.names = 1)

###### Read the input files from the STEPWAT_DIST directory ########
phen.data <- list()

for(index in 1:length(phen.files)){
  phen.data[[index]] <- read.table(phen.files[index], row.names = 1)
}

############## Convert the list to 2d and 3d arrays ################
# The 2d array represents the difference between the derived file 
# and the original (derived - original). It is used for printing.
# The 3d represents the derived values. It is used for graphing.
# The 3d array is easier to work with. The 2d is easier to print.
phen.data.2d <- matrix(nrow = nrow(phen.data[[1]]) * length(phen.files),
                       ncol = 14)
phen.data.2d[ ,2] <- rep(phen.files, each = nrow(phen.original))
phen.data.2d[ ,1] <- rep(row.names(phen.original),
                    length(phen.files))
colnames(phen.data.2d) <- c("RGroup", "File Name", month.abb)
for(i in 1:length(phen.data)){
  phen.data[[i]] <- data.matrix(phen.data[[i]])
  phen.data.2d[(nrow(phen.original)*(i-1)+1):(i*nrow(phen.original)),3:14] <- data.matrix(phen.data[[i]] - phen.original)
}

# phen.data is the 3d array
phen.data <- simplify2array(phen.data)

##################### Locate the "Current" file ####################
# We want to plot "Current" onto every graphic, so we separate it
# from phen.files
phen.current.index <- grep(phen.files, pattern = "urrent")
if(length(phen.current.index) == 1){
  phen.current.file <- phen.files[phen.current.index]
}
phen.files <- phen.files[!grepl(phen.files, pattern = "urrent")]

################### Create PHENOLOGY Graphics #######################
if(!file.exists("output/sxwphen_comparisons/graphics")){
  system("mkdir output/sxwphen_comparisons/graphics")
}

# Colors for each file. The number of colors required is (files.per.graphic + 2)
# to account for "original" and "Current".
colors <- c("blue", "black", "red", "green", "orange", "green4", 
            "brown", "purple", "aquamarine", "pink", "grey")

for(rgroup in 1:length(phen.original[, 1])){
  for(startFile in seq(from = 1, to = length(phen.files), 
                       by = files.per.graphic)){
    nextColor <- 2
    png(paste0("output/sxwphen_comparisons/graphics/", 
               row.names(phen.original)[rgroup], "_", 
               startFile, "-", 
               min(length(phen.data[1,1,]), startFile + files.per.graphic - 1),
               "_graph.png"), 
        width = 2048, height = 720)
    
    par(mfrow = c(1, 2))
    
    plot(x = c(1:12), y = t(phen.original[rgroup,]), xlab = "Month", 
         ylab = "Phenological Activity", 
         main = paste0(row.names(phen.original)[rgroup], 
                       " Phenological Activity Values by Month for ",
                       "Multiple Derived Files, with Original Value ",
                       "in Blue."),
         col = colors[1], type = "l", ylim = c(-.05, 1.2 * max(phen.data[rgroup, , ])), lwd = 2)
    
    # If a "Current" file is present, we want to add it to every graph.
    if(length(phen.current.index) == 1){
      points(x = c(1:12), 
             y = t(phen.data[rgroup, , phen.current.index]), 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 2)
      
      lines(x = c(1:12), 
            y = t(phen.data[rgroup, , phen.current.index]), 
            col = colors[nextColor], 
            lwd = 2)
      
      nextColor <- nextColor + 1
    }
    
    for(file in startFile:min(length(phen.files), 
                              startFile + files.per.graphic - 1)){
      # Add this scenario to the graph
      points(x = c(1:12), 
             y = t(phen.data[rgroup, , file + 1]), 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 2) # 3 and 2 fit well in a 1080 image
      
      nextColor <- nextColor + 1
    }
    
    legend.values <- simplify2array(
      strsplit(phen.files[startFile:min(
        length(phen.files), startFile + files.per.graphic - 1)], "\\."))[3:5, ]
    
    legend.values <- apply(legend.values, 2, paste0, collapse = ".")
    
    if(length(phen.current.index) == 1){
      legend.values <- c("Current", legend.values)
    }
    
    legend("topright",
           legend.values,
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    #################### Add the temperature graph #################
    plot(x = c(1:12), y = temperature.original, xlab = "Month", 
         ylab = "Temperature", 
         main = "Mean Monthly Temperature for each Climate Scenario with original temperature in blue",
         col = colors[1], type = "l", ylim = c(-10, 35), lwd = 2)
    
    climateIndexes <- c()
    for(row in 1:length(legend.values)){
      climateIndexes[row] <- fileName2climateIndex(legend.values[row], temperature.derived)
      addTemperatureLine(temperature.derived[climateIndexes[row], ], colors[row + 1])
      addTemperaturePoint(temperature.derived[climateIndexes[row], ], colors[row + 1], row)
    }
    
    legend("topleft",
           row.names(temperature.derived)[climateIndexes],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  } # END for each file
} # END for each RGroup

###################### Write the CSV file ##########################
write.csv(phen.data.2d, 
          paste0("output/sxwphen_comparisons/", 
                 "Derived_Files-Original.csv"), row.names = FALSE)

####################################################################################
########################## Compare sxwprod_v2.in files #############################
####################################################################################
if(!file.exists("output/sxwprod_comparisons")){
  system("mkdir output/sxwprod_comparisons")
}

########## Locate the sxwprod files that were generated ############
prod.files <- list.files(".", pattern = "sxwprod")

############## Read the original input CSV files ###################
litter.original <- read.csv("../../inputs/InputData_Litter.csv", row.names = 1)
biomass.original <- read.csv("../../inputs/InputData_Biomass.csv", row.names = 1)
pctlive.original <- read.csv("../../inputs/InputData_PctLive.csv", row.names = 1)

litter.list <- list(); biomass.list <- list(); pctlive.list <- list()

################ Loop through the generated files ##################
for(index in 1:length(prod.files)){
  prod.data <- read.table(prod.files[index], fill = TRUE)
  number.rgroups <- sum(prod.data[ , 1] != "[end]") / 3
  rgroup.names <- prod.data[1:number.rgroups, 1]
  
  litter.list[[index]] <- prod.data[1:number.rgroups, 2:ncol(prod.data)]
  row.names(litter.list[[index]]) <- rgroup.names
  
  biomass.list[[index]] <- prod.data[(number.rgroups + 2):(number.rgroups * 2 + 1), 2:ncol(prod.data)]
  row.names(biomass.list[[index]]) <- rgroup.names
  
  pctlive.list[[index]] <- prod.data[(number.rgroups * 2 + 3):(number.rgroups * 3 + 2), 2:ncol(prod.data)]
  row.names(pctlive.list[[index]]) <- rgroup.names
}

############### Create 2d matrix for printing ####################
pctlive.2d <- matrix(nrow = (nrow(pctlive.list[[1]]) * length(pctlive.list)), ncol = 14)
colnames(pctlive.2d) <- c("RGroup", "File", month.abb)

biomass.2d <- matrix(nrow = (nrow(biomass.list[[1]]) * length(biomass.list)), ncol = 14)
colnames(biomass.2d) <- c("RGroup", "File", month.abb)

litter.2d <- matrix(nrow = (nrow(litter.list[[1]]) * length(litter.list)), ncol = 14)
colnames(litter.2d) <- c("RGroup", "File", month.abb)

for(index in 1:length(prod.files)){
  litter.rows <- (nrow(litter.original)*(index-1)+1):(index*nrow(litter.original))
  litter.2d[litter.rows,2] <- rep(prod.files[index], times = nrow(litter.original))
  litter.2d[litter.rows,1] <- rownames(litter.original)
  litter.2d[litter.rows,3:14] <- data.matrix(litter.list[[index]] - litter.original)
  
  biomass.rows <- (nrow(biomass.original)*(index-1)+1):(index*nrow(biomass.original))
  biomass.2d[biomass.rows,2] <- rep(prod.files[index], times = nrow(biomass.original))
  biomass.2d[biomass.rows,1] <- rownames(biomass.original)
  biomass.2d[biomass.rows,3:14] <- data.matrix(biomass.list[[index]] - biomass.original)
  
  pctlive.rows <- (nrow(pctlive.original)*(index-1)+1):(index*nrow(pctlive.original))
  pctlive.2d[pctlive.rows,2] <- rep(prod.files[index], times = nrow(pctlive.original))
  pctlive.2d[pctlive.rows,1] <- rownames(pctlive.original)
  pctlive.2d[pctlive.rows,3:14] <- data.matrix(pctlive.list[[index]] - pctlive.original)
}

##################### Write the CSV files ########################
write.csv(pctlive.2d, 
          paste0("output/sxwprod_comparisons/PCTLIVE.", 
                 "derived-original.csv"),
          row.names = FALSE)
write.csv(biomass.2d, 
          paste0("output/sxwprod_comparisons/BIOMASS.", 
                 "derived-original.csv"),
          row.names = FALSE)
write.csv(litter.2d, 
          paste0("output/sxwprod_comparisons/LITTER.", 
                 "derived-original.csv"),
          row.names = FALSE)

##################### Locate the "Current" file ####################
# We want to plot "Current" onto every graphic, so we separate it
# from prod.files
prod.current.index <- grep(prod.files, pattern = "urrent")
if(length(prod.current.index) == 1){
  prod.current.file <- prod.files[prod.current.index]
}
prod.files <- prod.files[!grepl(prod.files, pattern = "urrent")]


#################### Create LITTER Graphics ########################
if(!file.exists("output/sxwprod_comparisons/LITTER_graphics")){
  system("mkdir output/sxwprod_comparisons/LITTER_graphics")
}

for(rgroup in 1:nrow(litter.original)){
  for(startFile in seq(from = 1, to = length(prod.files), 
                       by = files.per.graphic)){
    nextColor <- 2
    png(paste0("output/sxwprod_comparisons/LITTER_graphics/", 
               rgroup.names[rgroup], "_LITTER_", startFile, "-", 
               min(length(prod.files), startFile + files.per.graphic - 1),
               "_graph.png"), 
        width = 2048, height = 720)
    
    par(mfrow = c(1, 2))
    
    plot(x = c(1:12), y = t(litter.original[rgroup, ]), xlab = "Month", 
         ylab = "LITTER", 
         main = paste0(rgroup.names[rgroup], 
                       " Litter Values for Derived Files by Month, ",
                       "Compared to Original Value in Blue"),
         col = colors[1], type = "l", ylim = c(-0.08, 1), lwd = 2)
    
    if(length(prod.current.index) == 1){
      points(x = c(1:12), 
             y = litter.list[[prod.current.index]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      
      lines(x = c(1:12), 
            y = litter.list[[prod.current.index]][rgroup, ], 
            col = colors[nextColor], 
            lwd = 2)
      
      nextColor <- nextColor + 1
    }
    
    for(file in startFile:min(length(prod.files), 
                              startFile + files.per.graphic - 1)){
      points(x = c(1:12), 
             y = litter.list[[file + 1]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      
      nextColor <- nextColor + 1
    }
    
    legend.values <- simplify2array(
      strsplit(prod.files[startFile:min(
        length(prod.files), startFile + files.per.graphic - 1)], "\\."))[3:5, ]
    
    legend.values <- apply(legend.values, 2, paste0, collapse = ".")
    
    if(length(phen.current.index == 1)){
      legend.values <- c("Current", legend.values)
    }

    legend("topright",
           legend.values,
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    #################### Add the temperature graph #################
    plot(x = c(1:12), y = temperature.original, xlab = "Month", 
         ylab = "Temperature", 
         main = "Mean Monthly Temperature for each Climate Scenario with original temperature in blue",
         col = colors[1], type = "l", ylim = c(-10, 35), lwd = 2)
    
    climateIndexes <- c()
    for(row in 1:length(legend.values)){
      climateIndexes[row] <- fileName2climateIndex(legend.values[row], temperature.derived)
      addTemperatureLine(temperature.derived[climateIndexes[row], ], colors[row + 1])
      addTemperaturePoint(temperature.derived[climateIndexes[row], ], colors[row + 1], row)
    }
    
    legend("topleft",
           row.names(temperature.derived)[climateIndexes],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  }
}

#################### Create BIOMASS Graphics #######################
if(!file.exists("output/sxwprod_comparisons/biomass_graphics")){
  system("mkdir output/sxwprod_comparisons/biomass_graphics")
}

for(rgroup in 1:nrow(biomass.original)){
  for(startFile in seq(from = 1, to = length(prod.files), by = files.per.graphic)){
    nextColor <- 2
    png(paste0("output/sxwprod_comparisons/biomass_graphics/", 
               row.names(biomass.original)[rgroup], 
               "_", startFile, "-", 
               min(length(prod.files), startFile + files.per.graphic - 1),
               "_biomass_graph.png"), 
        width = 2048, height = 900)
    
    par(mfrow = c(1, 2))
    
    plot(x = c(1:12), y = t(biomass.original[rgroup, ]), xlab = "Month", 
         ylab = "Biomass value", 
         main = paste0(row.names(biomass.original)[rgroup],
                       " Biomass Values by Month for Derived Files, ", 
                       "Compared to Original Value in Blue"),
         col = colors[1], type = "l", ylim = c(-.08, 1.25), lwd = 2)
    
    if(length(prod.current.index) == 1){
      points(x = c(1:12), 
             y = biomass.list[[prod.current.index]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      
      lines(x = c(1:12), 
            y = biomass.list[[prod.current.index]][rgroup, ], 
            col = colors[nextColor], 
            lwd = 2)
      
      nextColor <- nextColor + 1
    }
    
    for(file in startFile:min(length(prod.files), 
                              startFile + files.per.graphic - 1)){
      points(x = c(1:12), 
             y = biomass.list[[file + 1]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      
      nextColor <- nextColor + 1
    }
    
    legend.values <- simplify2array(
      strsplit(prod.files[startFile:min(
        length(prod.files), startFile + files.per.graphic - 1)], "\\."))[3:5, ]
    
    legend.values <- apply(legend.values, 2, paste0, collapse = ".")
    
    if(length(phen.current.index == 1)){
      legend.values <- c("Current", legend.values)
    }
    
    legend("topleft",
           legend.values,
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    #################### Add the temperature graph #################
    plot(x = c(1:12), y = temperature.original, xlab = "Month", 
         ylab = "Temperature", 
         main = "Mean Monthly Temperature for each Climate Scenario with original temperature in blue",
         col = colors[1], type = "l", ylim = c(-10, 35), lwd = 2)
    
    climateIndexes <- c()
    for(row in 1:length(legend.values)){
      climateIndexes[row] <- fileName2climateIndex(legend.values[row], temperature.derived)
      addTemperatureLine(temperature.derived[climateIndexes[row], ], colors[row + 1])
      addTemperaturePoint(temperature.derived[climateIndexes[row], ], colors[row + 1], row)
    }
    
    legend("topleft",
           row.names(temperature.derived)[climateIndexes],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  }
}

#################### Create PCTLIVE Graphics #######################
if(!file.exists("output/sxwprod_comparisons/pctlive_graphics")){
  system("mkdir output/sxwprod_comparisons/pctlive_graphics")
}

for(rgroup in 1:nrow(pctlive.original)){
  for(startFile in seq(from = 1, to = length(prod.files), by = files.per.graphic)){
    nextColor <- 2
    png(paste0("output/sxwprod_comparisons/pctlive_graphics/", 
               row.names(pctlive.original)[rgroup], "_",
               startFile, "-", 
               min(length(prod.files), startFile + files.per.graphic - 1),
               "_pctlive_graph.png"), 
        width = 2048, height = 720)
    
    par(mfrow = c(1, 2))
    
    plot(x = c(1:12), y = t(pctlive.original[rgroup, ]), xlab = "Month", 
         ylab = "% Live Value", 
         main = paste0(row.names(pctlive.original)[rgroup],
                       " % Live Values for Derived Files, Compared to Original Value in Blue"),
         col = colors[1], type = "l", ylim = c(-0.08, 1), lwd = 2)
    
    if(length(prod.current.index) == 1){
      points(x = c(1:12), 
             y = pctlive.list[[prod.current.index]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      
      lines(x = c(1:12), 
            y = pctlive.list[[prod.current.index]][rgroup, ], 
            col = colors[nextColor], 
            lwd = 2)
      
      nextColor <- nextColor + 1
    }
    
    for(file in startFile:min(length(prod.files), startFile + files.per.graphic - 1)){
      points(x = c(1:12), 
             y = pctlive.list[[file]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      
      nextColor <- nextColor + 1
    }
    
    legend.values <- simplify2array(
      strsplit(prod.files[startFile:min(
        length(prod.files), startFile + files.per.graphic - 1)], "\\."))[3:5, ]
    
    legend.values <- apply(legend.values, 2, paste0, collapse = ".")
    
    if(length(phen.current.index == 1)){
      legend.values <- c("Current", legend.values)
    }
    
    legend("topright",
           legend.values,
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    #################### Add the temperature graph #################
    plot(x = c(1:12), y = temperature.original, xlab = "Month", 
         ylab = "Temperature", 
         main = "Mean Monthly Temperature for each Climate Scenario with original temperature in blue",
         col = colors[1], type = "l", ylim = c(-10, 35), lwd = 2)
    
    climateIndexes <- c()
    for(row in 1:length(legend.values)){
      climateIndexes[row] <- fileName2climateIndex(legend.values[row], temperature.derived)
      addTemperatureLine(temperature.derived[climateIndexes[row], ], colors[row + 1])
      addTemperaturePoint(temperature.derived[climateIndexes[row], ], colors[row + 1], row)
    }
    
    legend("topleft",
           row.names(temperature.derived)[climateIndexes],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  }
}
